Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
